### ISSUE TITLE
Questions about bundle size

### ISSUE THREAD

**Issue by callumlocke** [sheshbabu/rustmart-yew-example#1]
Thanks for making this demo, it's really interesting! I know very little about Rust, and haven't had time to work through your tutorial yet, but I'm interested in performance characteristics for using Rust in browsers via wasm and thought you might be able to shed some light. The main compiled bundle at `https://rustmart-yew.netlify.app/wasm_bg.wasm` is 136kB (488kB uncompressed), which seems pretty high for a small app like this, so I'm wondering what makes up the bulk of it. Obviously bundle size isn't the only performance concern, but I'm curious as to whether the size is due to bundled dependencies, or is there just a lot of unavoidable overhead when compiling Rust to wasm? And does the bundle size increase proportionally as the application source becomes more complex?

**Comment by sheshbabu** [comment]
Hi @callumlocke, thanks for checking out the demo! 

The bundle size is definitely huge for an application this size. This is because the wasm bundle also includes runtime and dependencies. But on the good side, 136KB of wasm is not same as 136KB of JS as instead of `download => parse => compile => excecute` for JS, wasm just needs `download => decode => execute`. 

Here's a blog post that goes into more details - https://hacks.mozilla.org/2018/01/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler/

Cheers,
Shesh

**Comment by ywwhack** [comment]
V8 optimized parse and compile a lot past years, which may not slower than wasm's decode. More detail - https://v8.dev/blog/cost-of-javascript-2019

**Comment by ywwhack** [comment]
> 
>  But on the good side, 136KB of wasm is not same as 136KB of JS as instead of `download => parse => compile => excecute` for JS, wasm just needs `download => decode => execute`.
> 

V8 optimized parse and compile a lot past years, which may not slower than wasm's decode. See: https://v8.dev/blog/cost-of-javascript-2019
